# Global configuration of nomess
general:
    # DEV | PROD
    context: DEV
    # enable | disable. If status is disable, this application is in maintenance mod
    status: enable

    path:
        default_error_log: '%ROOT%var/log/error.log'
        default_cache: '%ROOT%var/cache/'
        default_config_component: '%ROOT%config/components/'

        # Application sources
        default_controller: '%ROOT%src/Controller/'
        default_repository: '%ROOT%src/Repository/'
        default_entity: '%ROOT%src/Entity/'
        default_filter: '%ROOT%src/Filter/'
        default_template: '%ROOT%templates/'

    overwrite_extension_config: .local
    # auto | enable | disable
    toolbar: auto

server:
    user: root

error_pages:
    template_engine: twig
    codes:
        403: path/to/403_error # Permission denied
        404: path/to/404_error # Not found
        405: path/to/405_error # Not allowed
        500: path/to/500_error # Internal server error
        503: path/to/503_error # Maintenance status

packages:
    nomess/cache: 'Nomess\Component\Cache\NomessInstaller'
    nomess/parameter: 'Nomess\Component\Parameter\NomessInstaller'
    nomess/orm: 'Nomess\Component\Orm\NomessInstaller'
    nomess/cli: 'Nomess\Component\Cli\NomessInstaller'
    nomess/parser: 'Nomess\Component\Parser\NomessInstaller'

