<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'NoMess\\Core\\ObserverInterface' => 'get1',
);

    protected function get1()
    {
        $object = new Web\WebRooter();
        return $object;
    }

}
